### ISSUE TITLE
Clarify message objects

### ISSUE THREAD

**Issue by arj03** [ssb-ngi-pointer/ssb-validate2-rsjs#24]
Would be awfully nice to know that these act as key value timestamp (kvt) in existing validate :)

**Comment by arj03** [comment]
I think this one might be solved by https://github.com/ssb-ngi-pointer/ssb-validate2-rsjs/issues/26

**Comment by mycognosist** [comment]
Indeed. Let's keep this one open for now so that I have a reminder to update the docs during the KV refactor (being explicit about exactly what form the 'message objects' must be in).
