### ISSUE TITLE
Compile to WebAssembly

### ISSUE THREAD

**Issue by mycognosist** [ssb-ngi-pointer/ssb-validate2-rsjs#4]
Leaving this as a prompt for further investigation in the future. Relevant link: [Compiling from Rust to WebAssembly](https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm)

> <@staltz> I was thinking if ssb-validate (sunrise choir) could be compiled to webassembly, since it doesn't have I/O, it's just computation, then it could run in ssb-browser-core?

> <@arj03> yeah was thinking the same. Wondering how the threading works

**Comment by mycognosist** [comment]
Seems like a good time to post some updated notes on this process:

We are using [wasm-bindgen](https://github.com/rustwasm/wasm-bindgen) to generate bindings from our Rust code. This is primarily used via the `#[wasm_bindgen]` attribute (used to mark functions for export and assign a JS function name) which is used in much the same way as the `#[node_bindgen]` attribute in our `src/lib.rs` for native.

Then we use the [wasm-pack tool](https://github.com/rustwasm/wasm-pack) to "generate an npm wasm pkg from a rustwasm crate". `wasm-pack` uses `wasm_bindgen` under the hood.

Because our validation code relies on [ssb-validate (rs)](https://github.com/sunrise-choir/ssb-validate) - which employs parallelization with [rayon](https://github.com/rayon-rs/rayon)) - we use [wasm-bindgen-rayon](https://github.com/GoogleChromeLabs/wasm-bindgen-rayon) to auto-generate WebWorker shim code. These WebWorkers act as threads, with one WebWorker spawned for each thread invoked by the parallel validation code.

We are also using [module-workers-polyfill](https://unpkg.com/module-workers-polyfill@0.1.0/module-workers-polyfill.min.js) to add support for Firefox (more context can be found in [this issue](https://github.com/GoogleChromeLabs/wasm-bindgen-rayon/issues/8#issuecomment-847970589))

At this point, the WASM code for `ssb-validate2-rsjs` is working, but only due to some convenient bugs 🙃 Additional context [here](https://github.com/GoogleChromeLabs/wasm-bindgen-rayon/issues/8#issuecomment-847975700).

I am now working to move the WASM initialization and WebWorker threadpool initialization off the main thread. Contextual details appear in [this issue comment](https://github.com/GoogleChromeLabs/wasm-bindgen-rayon/pull/7#issuecomment-828530525).

**Comment by staltz** [comment]
@mycognosist I guess we can close this one? :)

**Comment by mycognosist** [comment]
@staltz Yes! :D

Just for the sake of any future readers:

We ended up using the Comlink library to move the WASM initialization and WebWorker threadpool initialization off the main thread. We also introduced bundling with webpack (https://github.com/ssb-ngi-pointer/ssb-validate2-rsjs-wasm/pull/1) which conveniently offers us hassle-free Firefox support (no polyfill needed).
